import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: The Robotic Nervous System',
      link: {
        type: 'doc',
        id: 'ros-2-nervous-system/introduction',
      },
      items: [
        'ros-2-nervous-system/nodes-topics-services',
        'ros-2-nervous-system/rclpy-communication',
        'ros-2-nervous-system/urdf-humanoid',
        'ros-2-nervous-system/launch-controllers-tf',
        'ros-2-nervous-system/summary',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: The Digital Twin',
      link: {
        type: 'doc',
        id: 'digital-twin/introduction',
      },
      items: [
        'digital-twin/physics-simulation',
        'digital-twin/building-worlds',
        'digital-twin/sensor-simulation',
        'digital-twin/unity-hri',
        'digital-twin/summary',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: The AI-Robot Brain',
      link: {
        type: 'doc',
        id: 'ai-robot-brain/introduction',
      },
      items: [
        'ai-robot-brain/isaac-sim-synthetic-data',
        'ai-robot-brain/isaac-ros-perception',
        'ai-robot-brain/vslam-navigation-mapping',
        'ai-robot-brain/nav2-biped-planning',
        'ai-robot-brain/summary',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Vision-Language-Action',
      link: {
        type: 'doc',
        id: 'vision-language-action/introduction',
      },
      items: [
        'vision-language-action/natural-language-to-actions',
        'vision-language-action/whisper-voice-commands',
        'vision-language-action/llm-cognitive-planning',
        'vision-language-action/summary',
      ],
    },
    'capstone-project',
  ],
};

export default sidebars;
